prepare trade/single form submit for response
eddb2-0/EDDB-2.0-frontend pull request #147
Opened 2024-05-30 15:46 UTC by aslink87

In order to start wiring together a UI to present the response for the form submission in this route, there are a few tasks that needed to be accomplished. This PR focuses on the following:

1. Create necessary types and Zod schema to validate both the form submit object, as well as the form response object on success

2. Update form submit object keys (ie: rename commodityDisplayName to commodityDisplayNames) to match the backend terminology

3. Establish form default values for a few inputs such as 'maxRouteDistance' to simplify the UX

4. update the hook we use to fetch data on form submits `useGetData` to require a response data type to be passed to it

2024-05-30 23:27 UTC, chrismou requested changes
Minor ux niggle otherwise all good 👍🏼

2024-05-30 23:27 UTC, chrismou commented on app/_components/trade-routes/single/Form.tsx
> +              <FormLabel>Max Distance From Star - LS</FormLabel>
Can we either stick "In LS" as the placeholder of the input as we do with some other fields, or put (in LS) in brackets (and if you opt for the latter do the same with any other fields where we specify the what unit is required). The - LS looks a bit strange as it is there

![image](https://github.com/ed-pilots-network/frontend/assets/319883/abc136f9-757a-438e-9006-68f1f3148cb5)

2024-06-01 17:46 UTC, aslink87 commented on app/_components/trade-routes/single/Form.tsx
> +              <FormLabel>Max Distance From Star - LS</FormLabel>
Establishing default values rules out the first. I'm happy to do the second. My question is, is it necessary at all? Do you think the values in these fields are self-explanatory enough that we can remove the designation entirely?

2024-06-03 08:36 UTC, chrismou commented on app/_components/trade-routes/single/Form.tsx
> +              <FormLabel>Max Distance From Star - LS</FormLabel>
I don't think having defaults necesarily rules out placeholders, tbh I sort of agree that most of them are intuitive enough, at least to not need it in the label. But using the placeholder is a good fallback for if the input is ever empty for whatever reason and you're not sure what to put in.

That said, does chakra provide any simple solutions for input groups, ie (from bootstrap)

![image](https://github.com/ed-pilots-network/frontend/assets/319883/5f0ab9fa-545a-4eac-b49b-9a5bf0d188eb)

2024-06-03 14:04 UTC, aslink87 commented on app/_components/trade-routes/single/Form.tsx
> +              <FormLabel>Max Distance From Star - LS</FormLabel>
How about...

![Selection_016](https://github.com/ed-pilots-network/frontend/assets/67390534/f23bf873-8f8f-40f5-b5c0-47204c26988b)

2024-06-03 14:16 UTC, chrismou commented on app/_components/trade-routes/single/Form.tsx
> +              <FormLabel>Max Distance From Star - LS</FormLabel>
Perfect, that looks really good imo 👍🏼

2024-06-03 14:16 UTC, chrismou approved these changes

2024-06-03 14:43 UTC, merged